accel: add -DDYNAMIC_DEBUG_MODULE to subdir-cflags - RFC
with DRM_USE_DYNAMIC_DEBUG=y now un-BROKEN

for configs like:
   CONFIG_DRM_USE_DYNAMIC_DEBUG=y
   # CONFIG_DYNAMIC_DEBUG is not set
   CONFIG_DYNAMIC_DEBUG_CORE=y

accel/amdxdna gets macro breakage:

                     from ../drivers/accel/amdxdna/aie2_ctx.c:8:
    ../drivers/accel/amdxdna/aie2_ctx.c: In function ‘aie2_hwctx_restart’:
    ../include/drm/drm_print.h:578:9: error: implicit declaration of function ‘_dynamic_func_call_cls’ [-Wimplicit-function-declaration]
      578 |         _dynamic_func_call_cls(cat, fmt, __drm_dev_dbg,         \
          |         ^~~~~~~~~~~~~~~~~~~~~~
    ../include/drm/drm_print.h:663:9: note: in expansion of macro ‘drm_dev_dbg’
      663 |         drm_dev_dbg(__drm_to_dev(drm), DRM_UT_DRIVER, fmt, ##__VA_ARGS__)
          |         ^~~~~~~~~~~
    ../include/drm/drm_print.h:681:33: note: in expansion of macro ‘drm_dbg_driver’
      681 | #define drm_dbg(drm, fmt, ...)  drm_dbg_driver(drm, fmt, ##__VA_ARGS__)
          |                                 ^~~~~~~~~~~~~~
    ../drivers/accel/amdxdna/amdxdna_pci_drv.h:15:41: note: in expansion of macro ‘drm_dbg’
       15 | #define XDNA_DBG(xdna, fmt, args...)    drm_dbg(&(xdna)->ddev, fmt, ##args)
          |                                         ^~~~~~~
    ../drivers/accel/amdxdna/aie2_ctx.c:76:17: note: in expansion of macro ‘XDNA_DBG’
       76 |                 XDNA_DBG(xdna, "hwctx is not ready, status %d", hwctx->status);
          |                 ^~~~~~~~

These sources include drm_print.h, which includes dynamic_debug.h and
then checks DRM_USE_DYNAMIC_DEBUG, to decide if drm_dbg() rides on
dynamic-debug underneath.

DRM_USE_DYNAMIC_DEBUG is possible with DYNAMIC_DEBUG_CORE alone, but
dynamic_debug.h also requires DYNAMIC_DEBUG_MODULE before defining
those macros above.

drm/Makefile already adds -DDYNAMIC_DEBUG_MODULE to cflags on behalf

amdxdna uses drm_dbg, so when built as a module with
DRM_USE_DYNAMIC_DEBUG=y, it needs this cflag in order to compile.  As
of HEAD~1, it gets the cflag from its own Makefile.

Signed-off-by: Jim Cromie <jim.cromie@gmail.com>